barcode_st01: D500
barcode_st02: D100
command_st01: D500
command_st02: D400
heartBeat: D100
plcTimeOut: '5'
printCount_st01: D100
printCount_st02: D100
printRecipe_st01: D100
printRecipe_st02: D100
respReg_st01: D100
respReg_st02: D100
scanTime: '3'
serialNo_st01: D100
serialNo_st02: D100
